- name: Pruning docker environment
  docker_prune:
    volumes: yes
    images: yes
    images_filters:
      dangling: true

- name: Stopping openhab
  docker_container:
    name: openhab
    state: stopped

- name: Stopping deconz
  docker_container:
    name: deconz
    state: stopped

- name: Creating backup of openhab volumes
  archive:
    path: /opt/openhab
    dest: "/opt/backup/openhab-{{ ansible_date_time.iso8601 }}.tar"
    format: tar
    owner: "{{ user }}"

- name: Creating backup of deconz volumes 
  archive:
    path: /opt/deconz
    dest: "/opt/backup/deconz-{{ ansible_date_time.iso8601 }}.tar"
    format: tar
    owner: "{{ user }}"