- name: Creating nginx container
  docker_container:
    name: nginx
    image: nginxproxy/nginx-proxy
    network_mode: nginx_network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_conf.d:/etc/nginx/conf.d/
      - nginx_vhost.d:/etc/nginx/vhost.d
      - nginx_htpasswd:/etc/nginx/htpasswd
      - nginx_html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    env:
      "DHPARAM_BITS": "4096"
      "DHPARAM_GENERATION": "false"
    restart_policy: always
    state: started
