---
collections:
  - name: community.general
  - name: community.docker
  - name: ansible.posix

roles:
  - src: https://github.com/JCSynthTux/ansible-role-docker-nginx
    name: nginx
  - src: https://github.com/geerlingguy/ansible-role-docker
    name: geerlingguy.docker