---
collections:
  - name: community.general
  - name: community.docker

roles:
  - src: https://github.com/JCSynthTux/ansible-role-debian-initial-setup
    name: Initial_setup
  - src: https://github.com/JCSynthTux/ansible-role-docker-nginx
    name: nginx
  - src: https://github.com/geerlingguy/ansible-role-docker
    name: geerlingguy.docker
  - src: https://github.com/geerlingguy/ansible-role-pip
    name: geerlingguy.pip
  - src: https://github.com/geerlingguy/ansible-role-docker_arm
    name: geerlingguy.docker_arm