---
collections:
  - name: community.general
  - name: community.docker

roles:
  - name: singleplatform-eng.users
  - name: grog.package
  - name: geerlingguy.security
  - src: https://github.com/JCSynthTux/ansible-role-docker-nginx
    name: nginx
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: geerlingguy.docker_arm
