---
- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
  
  roles:
    - role: Initial_setup
    - role: geerlingguy.docker
    - role: nginx
    - role: openhab 
    - role: deconz
    - role: mqtt
