---
- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - role: singleplatform-eng.users
    - role: grog.package
    - role: geerlingguy.security
    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
    - role: geerlingguy.docker_arm
      when: ansible_architecture == "aarch64"
    - role: geerlingguy.pip
    - role: nginx
    - role: openhab 
    - role: deconz
    - role: mqtt
    - role: backup
