- name: Copy openhab conf
  copy:
    src: "{{ role_path }}/files/openhab/conf/"
    dest: /opt/openhab/conf/
    owner: openhab
    group: openhab
    mode: '0775'
  notify: Restart OpenHAB container

- name: Copy openhab addons.config
  copy:
    src: "{{ role_path }}/files/openhab/addons.config"
    dest: /opt/openhab/userdata/config/org/openhab
    owner: openhab
    group: openhab
    mode: '0775'
  notify: Restart OpenHAB container