- name: Spawn openhab container
  docker_container:
    name: openhab
    image: openhab/openhab:latest
    network_mode: nginx_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/openhab/conf:/openhab/conf
      - /opt/openhab/userdata:/openhab/userdata 
      - /opt/openhab/addons:/openhab/addons
    ports:
      - "8080:8080"
    env:
      "UID": "9001"
      "GID": "9001"
      "OPENHAB_HTTP_PORT": "8080"
      "VIRTUAL_PORT": "8080"
      "VIRTUAL_HOST": "{{ openhab_host }}"
      "EXTRA_JAVA_OPTS": "-Duser.timezone={{ timezone }}"
    restart_policy: always
    labels:
      "docker-volume-backup.stop-during-backup": "true"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://{{ openhab_host }}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    state: "{{ 'started' if openhab_install is true else 'absent' }}"
