- name: Ensure group "openhab" exists with correct gid
  group:
    name: openhab
    state: present
    gid: 9001

- name: Create user "openhab"  
  user:
    name: openhab
    uid: 9001
    group: openhab
    shell: /sbin/nologin
    create_home: no
    append: yes
    state: present
  become: true

- name: Add users to openhab group
  user:
    name: "{{ item }}"
    groups: 
      - openhab
    append: yes
  with_items: "{{ smarthome_users }}"
