- name: Stop deconz container
  docker_container:
    name: deconz
    state: stopped

- name: Copy deconz configs
  copy:
    src: "{{ role_path }}/files/deconz_config/"
    dest: /opt/deconz/
    owner: deconz
    group: deconz
    mode: '0644'

- name: Start deconz container
  docker_container:
    name: deconz
    state: started