- name: Create a deconz container
  docker_container:
    name: deconz
    image: deconzcommunity/deconz
    network_mode: nginx_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/deconz:/opt/deCONZ
    devices:
      - "{{ deconz_controller }}:/dev/ttyUSB0:rwm"  
    env:
      "DECONZ_UID": "8001"
      "DECONZ_GID": "8001"
      "VIRTUAL_PORT": "80"
      "VIRTUAL_HOST": "{{ deconz_host }}"
    restart_policy: always
  when: not result.exists