- name: Ensure group deconz group exists
  group:
    name: deconz
    state: present
    gid: 8001
  when: deconz_install is defined and deconz_install == true

- name: Create user deconz  
  user:
    name: deconz
    uid: 8001
    group: deconz
    groups:
      - dialout
    shell: /sbin/nologin
    create_home: no
    append: yes
    state: present
  become: true
  when: deconz_install is defined and deconz_install == true

- name: Add users to deconz group
  user:
    name: "{{ item }}"
    groups: 
      - deconz
    append: yes
  with_items: "{{ smarthome_users }}"
  when: deconz_install is defined and deconz_install == true
