- name: Installing common packages
  apt:
    name: 
      - curl
      - git
      - neofetch
      - htop
      - wget
    update_cache: yes  
    state: present

- name: Updating packages to latest version
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: Removing useless packages from the cache
  apt:
    autoclean: yes

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes