- name: Disable root login over SSH
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no" 
    state: present
  notify: Restarting sshd

- name: Disable password login
  lineinfile: 
    path: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication no"
    state: present
  notify: Restarting sshd
